### ISSUE TITLE
Hint for Galois Field doesn’t parse

### ISSUE THREAD

**Issue by gitonthescene** [kparc/kcc#21]
FWIW, this is what I get from running the WASM version on an iPhone running iOS 15.1:

![4CC339A2-D6CB-4F31-81C9-9FF01BFE299D](https://user-images.githubusercontent.com/45531702/148713334-cd716b7d-99bb-44ba-94a8-d57b38740e4e.jpeg)

**Comment by gitonthescene** [comment]
There’s also a typo later on.  I’m not sure if that’s worth a separate issue:

> As you see, native sort is trendously faster, since it is using a very efficient sorting implementation. 

It should be “tremendously”.  I’ll post a pull request when I’m in front of my desktop.

**Comment by gitonthescene** [comment]
Also the tutorial now has an example of cut `^` so perhaps it should have a bullet at the bottom.

**Comment by gitonthescene** [comment]
I should also mention I found tutorial extremely well written.  Thanks so much for doing this.

**Comment by kelas** [comment]
> I should also mention I found tutorial extremely well written. Thanks so much for doing this.

thank you. yes, some people say it is quite a sweetheart.

sadly, as you can clearly see, it is a perpetual WIP.

thanks for stopping by.

**Comment by kelas** [comment]
> Also the tutorial now has an example of cut `^` so perhaps it should have a bullet at the bottom.

oh, right. could you be bothered to pr a fix?

**Comment by kelas** [comment]
> There’s also a typo later on. I’m not sure if that’s worth a separate issue:
> 
> > As you see, native sort is trendously faster, since it is using a very efficient sorting implementation.
> 
> It should be “tremendously”. I’ll post a pull request when I’m in front of my desktop.

my command of your language fails me all time time.

**Comment by kelas** [comment]
> FWIW, this is what I get from running the WASM version on an iPhone running iOS 15.1:

it is a bit of an easter egg :) ascii cast is possible. see if you can figure it out, and suggest a fix :)

**Comment by gitonthescene** [comment]
Sure.  I’ll post fixes hopefully later today.

**Comment by kelas** [comment]
> Sure. I’ll post fixes hopefully later today.

please also note that wasm build at kparc.io/k is ancient. i recommend using official builds

**Comment by gitonthescene** [comment]
I still haven’t grokked it yet but changing the final flip to an each makes it work.

![3FE83040-AC08-4C3F-9B7F-478869A2F199](https://user-images.githubusercontent.com/45531702/148724832-21b818fc-1c7d-4320-ab3d-d24f9ff2f2e2.jpeg)

FWIW, this type is not discussed in the tutorial:
```
 @2\32 458 1172 1443 275
`LI
 @+2\32 458 1172 1443 275
`LI
```
I'm assuming this hint used to work.

P.S. My battery life is a proxy for seeing how many tries it took.  :D

**Comment by gitonthescene** [comment]
> > Sure. I’ll post fixes hopefully later today.
> 
> please also note that wasm build at kparc.io/k is ancient. i recommend using official builds

FWIW, I had issues with the npm install which I noted [here](https://github.com/kparc/k/issues/23).

**Comment by kelas** [comment]
> > > Sure. I’ll post fixes hopefully later today.
> > 
> > 
> > please also note that wasm build at kparc.io/k is ancient. i recommend using official builds
> 
> FWIW, I had issues with the npm install which I noted [here](https://github.com/kparc/k/issues/23).

>  issues with the npm install

sadly, this one is above our head. it is used to work very well, note the past tense.

the time has come to decommission it, thanks for the heads up.

**Comment by kelas** [comment]
> > Sure. I’ll post fixes hopefully later today.
> 
> please also note that wasm build at kparc.io/k is ancient. i recommend using official builds

would you like to join the conversation on kparc.slack.com?

**Comment by gitonthescene** [comment]
> > > Sure. I’ll post fixes hopefully later today.
> > 
> > 
> > please also note that wasm build at kparc.io/k is ancient. i recommend using official builds
> 
> would you like to join the conversation on kparc.slack.com?

Very much so.  Thanks.

**Comment by gitonthescene** [comment]
> > would you like to join the conversation on kparc.slack.com?
> 
> Very much so. Thanks.
I wasn’t able to log on with that link alone.  Is there a way for me to reach out somehow for access?

**Comment by gitonthescene** [comment]
> > would you like to join the conversation on kparc.slack.com?
> 
> Very much so. Thanks. I wasn’t able to log on with that link alone. Is there a way for me to reach out somehow for access?

@kelas Is the google group the right place to follow up on this?
